name: Integration tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: 'localhost:5000'
      REGISTRY: 'localhost:5000'
      DOCKER_BUILDKIT: '0'
    strategy:
      fail-fast: false
      matrix:
        make-target:
        - integration-test-layers
        - integration-test-misc
        - integration-test-run
        - k8s-executor-build-push integration-test-k8s

    steps:
    - name: Maximize build space
      uses: AdityaGarg8/remove-unwanted-software@v3
      with:
        remove-android: 'true'
        remove-dotnet: 'true'
        remove-haskell: 'true'
    - name: Upgrade docker
      run: |
        sudo apt-get remove -y docker docker-engine docker.io containerd runc docker-doc docker-compose docker-compose-v2 podman-docker 
        sudo apt-get update -y
        sudo apt-get install -y \
          ca-certificates \
          curl \
          gnupg \
          lsb-release

        # Add Docker's official GPG key
        sudo install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
          sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

        echo \
          "deb [arch=$(dpkg --print-architecture) \
          signed-by=/etc/apt/keyrings/docker.gpg] \
          https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

        # Update the package list again with the new repository
        sudo apt-get update -y

        # Install the latest version of Docker Engine, CLI, and containerd
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version: '1.22'
    - uses: actions/checkout@b0e28b5ac45a892f91e7d036f8200cf5ed489415 # v3
    - uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v1
      with:
        version: v0.17.1

    - run: make install-container-diff k3s-setup
    - run: make ${{ matrix.make-target }}
