name: Unit tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b0e28b5ac45a892f91e7d036f8200cf5ed489415 # v3
    - run: |
    docker run -it --rm -v $PWD:/src -e GOFLAGS=-buildvcs-false --workdir /src golang:1.22 make test
